from turtle import *
title("Demo Application")
color("blue")
shape("turtle")
bgcolor("red")
pencolor("green")
width("3")
forward(100)
left(90)
forward(100)
left(90)
forward(100)
left(90)
forward(100)
left(90)
mainloop()